up:
	docker compose up --remove-orphans -d

up-a:
	docker compose up --remove-orphans

up-f:
	docker compose up --build --remove-orphans

shell:
	docker compose exec api sh

down:
	docker compose down
